name: Auto Fetch API

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          persist-credentials : false

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    - name: Set Account Info
      run: echo '${{ secrets.Config }}' > config.py

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Main script
      shell: bash
      run: python 'Actions.py'
